apiVersion: v1
kind: Service
metadata:
  name: devops-toolkit-service
  namespace: devops-toolkit
spec:
  type: NodePort
  selector:
    app: devops-toolkit
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
